In [16]:
import numpy as np
n = 12
np.random.seed(42)
x_train =np.random.rand(n, 2)
x_train

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184]])

In [17]:
x_test = np.random.rand(n, 2)
x_test

array([[0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041],
       [0.60754485, 0.17052412],
       [0.06505159, 0.94888554],
       [0.96563203, 0.80839735],
       [0.30461377, 0.09767211],
       [0.68423303, 0.44015249],
       [0.12203823, 0.49517691],
       [0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228],
       [0.31171108, 0.52006802]])

In [18]:
actual_w = np.array([[1.], [-2.]])
actual_w

array([[ 1.],
       [-2.]])

In [19]:
y_train = np.dot(x_train, actual_w)
y_train

array([[-1.52688849],
       [-0.46532303],
       [-0.1559704 ],
       [-1.67426868],
       [-0.81503014],
       [-1.91923521],
       [ 0.40776442],
       [-0.18498405],
       [-0.74527062],
       [-0.15051326],
       [ 0.33286517],
       [-0.44057904]])

In [20]:
def calcuate_posterior_covariance(lambda_, variance, X_train, dimension):
    covariance = np.linalg.inv(lambda_ * np.eye(dimension) + (1 / variance) * (X_train.T).dot(X_train))
    return covariance

In [21]:
lambda_input = 1
variance_input = 1
dimension = x_train.shape[1]


In [22]:
covariance = calcuate_posterior_covariance(lambda_input, variance_input, x_train, dimension)
active = []

print("Covariance Matrix:\n {}".format(covariance))

indices = list(range(x_test.shape[0]))
print("Indices: {}".format(indices))

Covariance Matrix:
 [[ 0.36499356 -0.14411671]
 [-0.14411671  0.25408343]]
Indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [23]:
for i in range(0,5):
    variance_matrix = x_test.dot(covariance).dot(x_test.T)
    result = np.argmax(variance_matrix.diagonal())
    actual_row = indices[result]
    active.append(actual_row)
    np.concatenate((x_train, x_test[result].reshape(1, x_test[result].shape[0])))
    x_test = np.delete(x_test, (result), axis=0)
    indices.pop(result)
    covariance = calcuate_posterior_covariance(lambda_input, variance_input, x_train, dimension)
  

In [24]:
print(active)

[5, 4, 9, 7, 0]
