In [1]:
import numpy as np

In [2]:
n = 12

In [3]:
np.random.seed(42)
x = np.c_[np.random.rand(n, 2), np.ones(n)]
x

array([[0.37454012, 0.95071431, 1.        ],
       [0.73199394, 0.59865848, 1.        ],
       [0.15601864, 0.15599452, 1.        ],
       [0.05808361, 0.86617615, 1.        ],
       [0.60111501, 0.70807258, 1.        ],
       [0.02058449, 0.96990985, 1.        ],
       [0.83244264, 0.21233911, 1.        ],
       [0.18182497, 0.18340451, 1.        ],
       [0.30424224, 0.52475643, 1.        ],
       [0.43194502, 0.29122914, 1.        ],
       [0.61185289, 0.13949386, 1.        ],
       [0.29214465, 0.36636184, 1.        ]])

In [4]:
actual_w = np.array([[1.], [-2.], [3.]])
actual_w

array([[ 1.],
       [-2.],
       [ 3.]])

In [5]:
y = np.dot(x, actual_w)
y

array([[1.47311151],
       [2.53467697],
       [2.8440296 ],
       [1.32573132],
       [2.18496986],
       [1.08076479],
       [3.40776442],
       [2.81501595],
       [2.25472938],
       [2.84948674],
       [3.33286517],
       [2.55942096]])

## Ridge Regression

In [6]:
def find_w(x, y, l, variance):
    a = np.dot(x.T, x) + l * variance * np.identity(x.shape[1])
    a_inv = np.linalg.inv(a)
    b = np.dot(x.T, y)
    return np.dot(a_inv, b)

In [7]:
w = find_w(x, y, 3.0, 1.0 )
w

array([[0.85506666],
       [0.04468779],
       [1.63102329]])

In [8]:
print(np.dot(actual_w.T, actual_w))
print(np.dot(w.T, w))

[[14.]]
[[3.39337296]]
